const SHOW_BASKET='BASKET/SHOW_BASKET'
const SAVING_PROMO='BASKET/SAVING_PROMO'
const ADD_TO_SHOPPING_BAG='BASKET/ADD_TO_SHOPPING_BAG'
const REMOVE_FROM_SHOPPING_BAG='BASKET/REMOVE_FROM_SHOPPING_BAG'
const NAME='BASKET'
export {SHOW_BASKET,SAVING_PROMO,ADD_TO_SHOPPING_BAG, REMOVE_FROM_SHOPPING_BAG,NAME}
